### ISSUE TITLE
Generic Model Interface

### ISSUE THREAD

**Issue by abkslm** [USFCA-CS490-Micron/private-relay#3]
This is an HTTP and internal API.

It should:
- allow the client device to make a call for any service over the API
- call the necessary function to make an API call to the requested service (e.g. if `type` is `basic_question`, send it to GNL)
- wait for response, then return body of response to client

**Comment by n-t-eastham** [comment]
Since 'basic' questions are handled on device I'm using GNL to preprocess the 'complex' queries.
